delete from amenity where id > 0;
delete from AMENITY_TYPE where id > 0;
delete from apartment where id > 0;
delete from expense_type where id > 0;
delete from expenses where id > 0;
delete from NearestTransitPoint_Category where id >0;
delete from NearestTransitPointInterest where id >0;
delete from NTPI_Property where id > 0;
delete from NearestTransitPoint_Category where id >0;
delete from property where id > 0;
delete from PROPERTY_AMENITY_MAP where id > 0;
delete from Property_school where id > 0;
delete from PROPERTY_TYPE where id > 0;
delete from review where id > 0;
delete from school where id > 0;
delete from url where id>0;